# Generated by Django 5.2.4 on 2025-09-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_location_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="organization",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
