# Generated by Django 5.2.4 on 2025-09-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_league_organization_alter_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.league",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.site",
            ),
        ),
    ]
