# Generated by Django 5.2.4 on 2025-09-11 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_alter_game_league_alter_game_site"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-date"]},
        ),
    ]
