# Generated by Django 5.2.4 on 2025-09-12 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_game_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["date"]},
        ),
    ]
