# Generated by Django 5.2.4 on 2026-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0008_add_user_to_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
